add layoutCompose brench
VadimKravchenkoDev/FireGuardian pull request #4
Opened 2024-04-07 16:00 UTC by VadimKravchenkoDev

2024-04-07 18:36 UTC, Yazon2006 requested changes

2024-04-07 18:36 UTC, Yazon2006 commented on app/src/main/java/com/kravchenkovadim/fireguardian/data/AddTask.kt
> +    val isCheck: Boolean,
Що за поле?

2024-04-07 18:36 UTC, Yazon2006 commented on app/src/main/java/com/kravchenkovadim/fireguardian/data/AddTask.kt
> +data class AddTask (
Чому назва AddTask, а не просто Task?

2024-04-07 18:36 UTC, Yazon2006 commented on app/src/main/java/com/kravchenkovadim/fireguardian/data/AddTaskDao.kt
> +    fun getAllTasksById(taskId: Int): Flow<List<AddTask>>
Бачу що метод повертає Flow, тому краще назвати його не getAllTasksById, а observeAllTasksById

2024-04-07 18:36 UTC, Yazon2006 commented on app/src/main/java/com/kravchenkovadim/fireguardian/data/AddTaskRepoImpl.kt
> +) :AddTaskRepository{
Застосуй автоформат

2024-04-07 18:36 UTC, Yazon2006 commented on app/src/main/java/com/kravchenkovadim/fireguardian/data/DayListTasks.kt
> +    val id: Int? = null,
Це хіба не автоінкремент айді повинен бути?

2024-04-07 18:36 UTC, Yazon2006 commented on app/src/main/java/com/kravchenkovadim/fireguardian/data/DayListTasks.kt
> +    val allTasksCount: Int,
Це не зайві дані. При нявності звязку з тасками можна порахувати їх кількість

2024-04-07 18:36 UTC, Yazon2006 commented on app/src/main/java/com/kravchenkovadim/fireguardian/data/NoteItem.kt
> +    val time: String
Що за час?

2024-04-07 18:36 UTC, Yazon2006 commented on .idea/gradle.xml
всю папку .idea варто видалити з гіта, якшо ти додав її не навмисно

2024-04-08 04:43 UTC, VadimKravchenkoDev commented on app/src/main/java/com/kravchenkovadim/fireguardian/data/AddTask.kt
> +    val isCheck: Boolean,
Це будудь задачи типу на день, якщо виконано задачу то ставишь чек.

2024-04-08 04:45 UTC, VadimKravchenkoDev commented on app/src/main/java/com/kravchenkovadim/fireguardian/data/AddTask.kt
> +data class AddTask (
згоден, перепишу, зробив як на відео, а по факту це ж не метод який щось робить а просто таска

2024-04-08 04:51 UTC, VadimKravchenkoDev commented on app/src/main/java/com/kravchenkovadim/fireguardian/data/AddTaskDao.kt
> +    fun getAllTasksById(taskId: Int): Flow<List<AddTask>>
добре

2024-04-08 04:53 UTC, VadimKravchenkoDev commented on app/src/main/java/com/kravchenkovadim/fireguardian/data/AddTaskRepoImpl.kt
> +) :AddTaskRepository{
зробив

2024-04-08 04:55 UTC, VadimKravchenkoDev commented on app/src/main/java/com/kravchenkovadim/fireguardian/data/DayListTasks.kt
> +    val id: Int? = null,
@PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    val id: Int = 0
    ось так?

2024-04-08 04:56 UTC, VadimKravchenkoDev commented on app/src/main/java/com/kravchenkovadim/fireguardian/data/DayListTasks.kt
> +    val id: Int? = null,
я тоді і в інших так зроблю

2024-04-08 04:58 UTC, VadimKravchenkoDev commented on app/src/main/java/com/kravchenkovadim/fireguardian/data/DayListTasks.kt
> +    val id: Int? = null,
на відео де я дивлюсь як робити, автор просто сказав що воно автоматом буде рахувати

2024-04-08 05:03 UTC, VadimKravchenkoDev commented on app/src/main/java/com/kravchenkovadim/fireguardian/data/DayListTasks.kt
> +    val allTasksCount: Int,
я поки що не можу відповісти, роблю по учбовому проекту, якщо буде зайвим то приберу з часом

2024-04-08 05:03 UTC, VadimKravchenkoDev commented on app/src/main/java/com/kravchenkovadim/fireguardian/data/NoteItem.kt
> +    val time: String
час коли створено нотаток

2024-04-08 05:08 UTC, VadimKravchenkoDev commented on .idea/gradle.xml
добре, не знав про це
знайшов по цьому питанню інфу, дякую за підказку

2024-04-08 05:12 UTC, Yazon2006 commented on app/src/main/java/com/kravchenkovadim/fireguardian/data/NoteItem.kt
> +    val time: String
Тоді createdDate

2024-04-08 05:38 UTC, Yazon2006 approved these changes

2024-04-08 05:39 UTC, Yazon2006 approved these changes

2024-04-08 08:04 UTC, Yazon2006 approved these changes

2024-04-08 12:13 UTC, merged